# -*- coding: utf-8 -*-
"""Assignments_overview_(Part_2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HchT-iBLhy9VX3Zqe8PB8VcNz_tVdAh0
"""

try:
     from dlroms import*
except:
     !pip install --no-deps git+https://github.com/NicolaRFranco/dlroms.git
     from dlroms import*

import numpy as np

"""## **Linear elasticity**: material design for a stunt training facility"""

# FOM discretization
mesh = fe.unitsquaremesh(40, 40)
Vh = fe.space(mesh, 'CG', 1, vector_valued = True)
clc()

# Dataset (parameters and FOM simulations)
import gdown
gdown.download(id = "1XYPnIpVVc9jkd7LwMhC-FYoV2RTnTK8L", output = "floor.npz")
clc()

data = np.load("floor.npz")
mu, u = dv.tensor(data['mu'], data['u'])

# Auxiliary function for animation
def animated_warp(u, Vh):
  from dlroms.gifs import save as savegif
  rnd = np.random.randint(50000)
  def drawframe(i):
    plt.figure(figsize = (4, 4))
    fe.plot(u[i], Vh, axis = [-0.25, 1.25, -0.25, 1.25], warp = True)
    plt.title("t = %.2f" % (i*0.02))
    plt.axis("off")
  savegif(drawframe, len(u), "temp%d-gif" % rnd)
  from PIL import Image, ImageSequence
  path = "temp%d-gif.gif" % rnd
  with Image.open(path) as im:
    frames = [frame.copy() for frame in ImageSequence.Iterator(im)]
    frames[0].save(path, save_all=True, append_images=frames[1:], loop=0, duration=im.info.get('duration', 100))
  from IPython.display import Image, display
  display(Image("temp%d-gif.gif" % rnd))
  from os import remove
  remove("temp%d-gif.gif" % rnd)

# First simulation in the dataset
animated_warp(u[0], Vh)

# Fancy plot showing warping and displacement magnitude altogether

which = 7 # First simulation

ns, nt, nh = u.shape
t = list(np.linspace(0, 1, nt))

umod = u[which].reshape(nt, -1, 2).pow(2).sum(axis = -1).sqrt()
plt.figure(figsize = (12, 4))
for i, ti in enumerate([0, 10, 15]):
  plt.subplot(1, 3, i+1)
  warped_mesh = fe.warpmesh(u[which, ti], Vh)
  delta = mu[which].item()
  WVh = fe.space(warped_mesh, 'CG', 1)

  fe.plot(umod[ti], WVh, levels = 30, vmin = umod.min(), vmax = umod.max(), colorbar = True, shrink = 0.4)
  plt.axis([-0.25, 1.25, -0.25, 1.25])
  plt.title("t = %.2f" % t[ti])
  plt.axis("off")

ndata, ntimes, nh = u.shape
p = mu.shape[-1]
print("Trajectories:\t%d." % ndata)
print("Timesteps:\t%d." % ntimes)
print("FOM dimension:\t%d." % nh)
print("Parameters:\t%d." % p)

import numpy as np
import matplotlib.pyplot as plt

# # remove u[0] from u
# u = u[:,1:]
u_traj = u[0]  # shape: (51, 3362)

# Compute L2 norm over space at each time step
u_norms = np.linalg.norm(u_traj, axis=1)  # shape: (51,)

# Plot
plt.figure(figsize=(8, 4))
plt.plot(u_norms, marker='o')
plt.xlabel("Time step")
plt.ylabel(r"$\|u(t)\|_2$")
plt.title("Evolution of $u(t)$ over time (Trajectory 0)")
plt.grid(True)
plt.show()

mut = dv.zeros(ndata, ntimes, p+1)
times = dv.tensor(np.linspace(0, 1, ntimes))
for i in range(ndata):
    mut[i,:,:p] = mu[i] # Corrected slice based on actual p
    mut[i,:, p] = times # Assign times to the correct index

u = u.reshape(-1, nh)
u.shape

mut = mut.reshape(-1, p+1)
mut.shape

ntrain= 75*nt
from scipy.linalg import svd
X, s, Yt = svd(u[:ntrain].T, full_matrices = False)

plt.figure(figsize = (8, 3))
plt.subplot(1, 2, 1)
plt.plot(s[1:50])
plt.subplot(1, 2, 2)
plt.loglog(s)
plt.show()

import numpy as np

# Cumulative explained variance (excluding s[0])
cum_explained = np.cumsum(s[1:]**2) / np.sum(s[1:]**2)

# Find first index where variance ≥ 99%
k99 = np.argmax(cum_explained >= 0.999) + 1  # +1 to correct for index shift
print(f"To capture 99.9% of the variance, you need {k99} modes.")

l2 = L2(Vh)
clc()

def error(utrue, upred):
    return (l2(utrue-upred).reshape(-1, nt).sum(axis = -1)/l2(utrue).reshape(-1, nt).sum(axis = -1)).mean()

# Ex. 1.2
n = 15
V = X[:, :n]
V = dv.tensor(V)

uproj = u @ V @ V.T
print("u.shape: ", u.shape)
print("ntrain: ", ntrain)
print("u[ntrain:]: ", u[ntrain:].shape)

# uproj = u @ V @ V.T
# avg_proj_error = mre(euclidean)(u[ntrain:], uproj[ntrain:])
# print("Average projection error: %s." % num2p(avg_proj_error))

# Compute projection error using L2 norm over function space
avg_proj_error = error(u[ntrain:], uproj[ntrain:])

# Print as a percentage
print("Average projection error (L2): {:.2f}%".format(avg_proj_error * 100))

"""<mark>**POD-NN**</mark></br>"""

c = u @ V

c.shape

# Note: phi should go from mut (p+1-dimensional) to c (n-dimensional)
# p is already defined as mu.shape[1] which is 1
input_dim = p + 1

phi = Dense(input_dim, 50, gelu) + Dense(50, 50, gelu) + Dense(50, n, activation = None)
model = DFNN(phi)
model.He()
model.train(mut, c, ntrain = ntrain, epochs = 500, loss = mse(euclidean))

model.freeze()

uROM = model(mut[ntrain:]) @ V.T
print("Average relative error of POD-NN: %s." % num2p(error(u[ntrain:], uROM)))

"""
<mark>**DL-ROM**</mark></br>"""

import torch
import torch.nn.functional as F

from torch.optim import Adam

# Activation functions
rho_e = rho_d = relu
# Model parameters
latent = 5        # latent space dimension
hidden1 = 512
hidden2 = 512

# Define encoder and decoder
encoder = Dense(nh, hidden1, rho_e) + Dense(hidden1, hidden2, rho_e) + Dense(hidden2, latent, rho_e)
decoder = Dense(latent, hidden2, rho_d) + Dense(hidden2, hidden1, rho_d) + Dense(hidden1, nh, activation=None)

# Build the autoencoder model
autoencoder = DFNN(encoder + decoder)
autoencoder.He()
#autoencoder.cuda()

# Train the autoencoder
autoencoder.train(
    u, u,
    ntrain=ntrain,
    epochs=100,
    loss=mse(euclidean),
    optim=Adam,
    lr=1e-4,
    batchsize=64,
    notation='%'
)

# Freeze model for inference
autoencoder.freeze()

print("Autoencoder MRE: %s" % num2p(error(u[ntrain:], autoencoder(u[ntrain:]))))

V = dv.tensor(X[: , :latent])
print("POD MRE: %s" % num2p(error(u[ntrain:], u[ntrain:] @ V @ V.T)))

nu = encoder(u)

phi = DFNN(Dense(p+1, 500, gelu) + Dense(500, latent, activation = None))

phi.He()
phi.train(mut, nu, ntrain = ntrain, epochs = 200, loss = mse(euclidean))
phi.freeze()

dlrom = lambda mt: decoder(phi(mt))
num2p(error(u[ntrain:], dlrom(mut[ntrain:])))

# Reshape to (nsim, nt, nh)
u = u.reshape(ndata, ntimes, nh)

mu0 = mu[which]  # Get its parameter
ntimes = u.shape[1]
nh = u.shape[2]
times = np.linspace(0, 1, ntimes)

# Prepare DL-ROM input [ntimes, p+1]
p = mu.shape[-1]
mu0t = dv.zeros(ntimes, p+1)
mu0t[:, :p] = mu0
mu0t[:, p] = dv.tensor(times)

"""<mark>**POD DL-ROM**</mark></br>"""

from scipy.linalg import svd
u = u.reshape(-1, nh)

nr = 50
V = dv.tensor(svd(u[:ntrain].T.cpu().numpy(), full_matrices = False)[0][:, :nr]) ### <--- POD basis for POD-AE
ur = u @ V

from torch import tanh
from torch.optim import Adam

# Smooth bounded activation function
rho = lambda x: tanh(0.01 * x)  # smooth, bounded in [-1, 1]

# Network architecture
latent = 5
small_encoder = Dense(nr, 20, gelu) + Dense(20, latent, gelu)
small_decoder = Dense(latent, 20, gelu) + Dense(20, 40, gelu) + Dense(40, nr, activation=None)
small_ae = DFNN(small_encoder + small_decoder)  # Inner AE combining encoder & decoder

# Initialize and train
small_ae.unfreeze()
small_ae.He()

small_ae.train(
    ur, ur,
    loss=mse(euclidean),
    ntrain=ntrain,
    epochs=500,
    optim=Adam,
    lr=1e-4,
    batchsize=64,
    notation='%'
)

small_ae.freeze()

from dlroms.dnns import Matrix

encoder = Matrix(V.T) + small_encoder
decoder = small_decoder + Matrix(V)
ae = encoder + decoder

print("Autoencoder MRE: %s" % num2p(error(u[ntrain:], ae(u[ntrain:]))))

nu = encoder(u)
phi = DFNN(Dense(p+1, 200, gelu) +Dense(200, 200, gelu)+ Dense(200, latent, activation = None))

phi.He()
phi.train(mut, nu, ntrain = ntrain, epochs = 200, loss = mse(euclidean))
phi.freeze()

dlrom = lambda mt: decoder(phi(mt))
num2p(error(u[ntrain:], dlrom(mut[ntrain:])))

"""<mark>**AE+SINDy**</mark></br>"""

from torch import tanh
rho = lambda x: tanh(0.01*x) ### <-- smooth activation that bounds the dynamics within [-1,1]^n

latent = 2
small_encoder = Dense(nr, 20, gelu) + Dense(20, latent, rho)
small_decoder = Dense(latent, 20, gelu) + Dense(20, 40, gelu) + Dense(40, nr, activation = None)
small_ae = DFNN(small_encoder + small_decoder) ### <--- inner AE module, combining the "small encoder" and "small decoder"

small_ae.unfreeze()
small_ae.He()
small_ae.train(ur, ur, loss = mse(euclidean), ntrain = ntrain, epochs = 200)
small_ae.freeze()

from dlroms.dnns import Matrix

encoder = Matrix(V.T) + small_encoder
decoder = small_decoder + Matrix(V)
ae = encoder + decoder

z =  encoder(u) ### <--- latent representation of the solutions
t = np.arange(nt)*0.02

for i in range(10):
  plot(t, z.reshape(-1, nt, latent)[i][:, 0], color = 'steelblue', alpha = 1.0 - i/10, label = '$z_1$' if i==0 else None)

plt.legend()
plt.xlabel("t")
plt.title("AE latent dynamics")
None

from dlroms.dnns import Weightless
from torch import matmul

class Library(Weightless):
  def __init__(self, lib):
    super(Library, self).__init__()
    self.lib = lib

  def forward(self, x):
    from torch import cat
    nx = len(x)
    return cat([f(x).reshape(nx, -1) for f in self.lib], axis = -1)

class SINDy(ROM):
  def __init__(self, *args, **kwargs):
    from torch.nn import Parameter
    super(SINDy, self).__init__(*args, **kwargs)
    self.thr = Parameter(dv.tensor(0.0))

  def threshold(self, A0):
    # Hard-promotes sparsity by clamping values close to 0 (with a learnable threshold)
    return relu(A0-self.thr) - relu(-A0-self.thr)

  def A(self, mu):
    eta = self[0]
    A0 = eta(mu)
    return self.threshold(A0)

  def forward(self, mu, z):
    A = self.A(mu)
    theta = self.Xi(z).unsqueeze(-1)
    return matmul(A, theta).squeeze(-1), A

  def freeze(self, *args, **kwargs):
    super(SINDy, self).freeze(*args, **kwargs)
    self.thr.requires_grad_(False)

  def unfreeze(self, *args, **kwargs):
    super(SINDy, self).freeze(*args, **kwargs)
    self.thr.requires_grad_(True)

  def evolve(self, mu0, z0, steps, tau):
    from torch import atleast_2d
    mu0s = atleast_2d(mu0)
    z0s = atleast_2d(z0)

    many, n = z0s.shape
    zsindy = self.coretype().zeros(many, steps + 1, n)
    zsindy[:, 0] = z0s
    for j in range(steps):
      dzdtj = self.forward(mu0s, zsindy[:, j])[0]
      zsindy[:, j+1] = zsindy[:, j] + tau*dzdtj

    return zsindy

  def parameters(self, *args, **kwargs):
    return super(SINDy, self).parameters() + [self.thr]

  def He(self, *args, **kwargs):
    from torch.nn import Parameter
    super(SINDy, self).He(*args, **kwargs)
    self.thr = Parameter(dv.tensor(0.0))

def dt(zval):
  """Approximation of time derivatives via finite differences.
  Later used in the definition of the loss to approximate the true derivatives."""
  tau = 0.02
  zval = zval.reshape(-1, nt, latent)  # reshape to (nsim, nt, latent)
  # Central differences: use z_{i+1} - z_{i-1}
  zprev = zval[:, :-2, :]  # shape: (nsim, nt-2, latent)
  znext = zval[:, 2:, :]   # shape: (nsim, nt-2, latent)
  dzdt = (znext-zprev)/(2*tau)
  return dzdt

Xi = Library([
    lambda x: x,                    # Linear terms
    lambda x: x**2,                 # Quadratic terms
    lambda x: x[:, 0]*x[:, 1],      # Cross terms
    lambda x: x**3,                 # Cubic terms
    lambda x: x**4,                 # Quartic terms
    lambda x: x[:, 0]**2*x[:, 1],   # Higher-order cross terms
    lambda x: x[:, 0]*x[:, 1]**2,   # Higher-order cross terms
    lambda x: 1.0 + 0*x             # Constant term
])

m = Xi(dv.zeros(1, latent)).shape[-1] # m = 9
p = mu.shape[-1]

eta = Dense(p, 50, gelu) + Dense(50, 50, gelu) + Dense(50, m*latent, None) + Reshape(latent, m)
sindy = SINDy(eta, Xi = Xi)
sindy.He()

from torch.optim import Adam
def sindy_loss(ztrue, sindy_output):
  dzpred, A = sindy_output
  dzdt_true = dt(ztrue) ### <-- time derivatives of the true latent coordinates
  return mse(euclidean)(dzdt_true, dzpred.reshape(-1, nt, latent)[:, 1:-1].reshape(-1, latent)) + 0.01*A.abs().tanh().sum(axis = -1).sum(axis = -1).mean() # promotes sparsity via l1-penalty

def sindy_error(ztrue, sindy_output):
  dzpred, A = sindy_output
  dzdt_true = dt(ztrue) ### <-- time derivatives of the true latent coordinates
  return mse(euclidean)(dzdt_true, dzpred.reshape(-1, nt, latent)[:, 1:-1].reshape(-1, latent))

mu_repeated = (dv.zeros(ns, nt, 1) + mu.reshape(ns, 1, -1)).reshape(ns*nt, -1) ### <--- transforming [mu0, mu1, mu2, ...] onto [mu0, .., mu0, mu1, ... mu1, mu2, ....] for shape consistency with z
sindy.train(
    (mu_repeated, z), 
    z, 
    loss=sindy_loss, 
    error=sindy_error, 
    epochs=1000, 
    ntrain=ntrain, 
    optim=Adam, 
    lr=1e-4,  # Lower learning rate for better stability
    batchsize=nt, 
    shuffle=False
)